on:
  push:
    branches:
      - master

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # install dependencies, build, and test
    - name: npm install, build, and test
      working-directory: .
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: vdgrowthchartapp
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}